config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :projects do
    resources :tasks, only: [:index, :new, :create, :edit, :update, :destroy]
  end
  resources :users, only: [:index, :show]
  get "profile", to: "pages#profile"
  patch "profile", to: "pages#profile_update"
  get "contact_us", to: "pages#contact_us"

  get "close/:project_id/tasks/:id", to: "tasks#edit_to_close", as: :edit_task_to_close
  patch "/close/:project_id/tasks/:id", to: "tasks#close", as: :closetask

  resources :conversations do
    resources :messages
  end
  # resources :tasks, only: [ :show, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :project
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    @tasks = policy_scope(Task).where(project: params[:project_id])
    @project = Project.find(params[:project_id])
  end

  def new
    @task = Task.new
    @project = Project.find(params[:project_id])
    authorize @project
    authorize @task
  end

  def create
    @task = Task.new(task_params)
    @project = Project.find(params[:project_id])
    authorize @project
    authorize @task
    @task.project = @project
    @task.status = false
    #@task.user = current_user #the manager who affect the expert later
    if @task.save
      redirect_to project_tasks_path
    else
      render :new
    end

  end

  def edit
    @task = Task.find(params[:id])
    @project = Project.find(params[:project_id])
    #authorize @project
    authorize @task
  end

  def update
    @task = Task.find(params[:id])
    @project = Project.find(params[:project_id])
    #authorize @project
    authorize @task
    if @task.update(task_params)
      redirect_to project_tasks_path(@task.project)
    else
      redirect_to :edit
    end
  end

  def destroy
    @task = Task.find(params[:id])
    authorize @task
    if @task.destroy
      redirect_to project_tasks_path(@task.project)
    else
      redirect_to project_tasks_path
    end
  end

  def edit_to_close
    @task = Task.find(params[:id])
    @project = Project.find(params[:project_id])
    authorize @project
    authorize @task
  end

  def close
    @task = Task.find(params[:id])
    @project = Project.find(params[:project_id])
    authorize @project
    authorize @task
    if @task.update(end_date: task_params[:end_date], deadline: task_params[:deadline], work_hours: task_params[:work_hours], status: true)
      if close_project?(@project)
        @project.status = true
        @project.save
      end
      redirect_to project_tasks_path(@task.project)
    else
      redirect_to :edit_to_close
    end

  end


  private

  def close_project?(project)
    project.tasks.where(status: false).empty?
  end

  def task_params
    params.require(:task).permit(:title, :description, :start_date, :end_date, :deadline, :work_hours)
  end

end

app/views/tasks/_form.html.erb
<%= simple_form_for [@project, @task] do |f| %>


<%= f.input :title, label_html: {class: 'pull-left'} %>
<%= f.input :description, label_html: {class: 'pull-left'} %>
<%= f.input :start_date, label_html: {class: 'pull-left'}, as: :date, html5: true %>
<%= f.input :end_date, label_html: {class: 'pull-left'}, as: :date, html5: true %>
<%= f.input :deadline, label_html: {class: 'pull-left'}, as: :date, html5: true %>
<%= f.input :work_hours, label_html: {class: 'pull-left'} %>

<% if @task.id == nil %>
<%= f.submit "Add deliverable", class: "btn btn-primary" %>
<% else %>
<%#= f.input :work_hours, label_html: {class: 'pull-left'} %>
<%= f.submit "Update", class: "btn btn-primary" %>
<% end %>
<% end %>

app/views/tasks/edit.html.erb
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-sm-8 col-sm-offset-2">
                <div class="form-login">
                    <h2>Edit</h2>
                    <%= render 'form' %>
                    <%= link_to "Back", project_tasks_path %>
                </div>
            </div>
        </div>
    </div>

app/views/tasks/edit_to_close.html.erb
<div class="container">
    <div class="row">
        <div class="col-xs-12 col-sm-8 col-sm-offset-2">
            <div class="form-login">
                <%= simple_form_for [@project, @task], url: closetask_path(@project, @task), method: :patch do |f| %>
                <%= f.input :title, label_html: {class: 'pull-left'} %>
                <%= f.input :description, label_html: {class: 'pull-left'} %>
                <%= f.input :start_date, label_html: {class: 'pull-left'}, as: :date, html5: true %>
                <%= f.input :end_date, label_html: {class: 'pull-left'}, as: :date, html5: true %>
                <%= f.input :work_hours, label_html: {class: 'pull-left'} %>
                <%= f.submit "Mark complete", class: "btn btn-primary" %>
                <%#= f.input :work_hours, label_html: {class: 'pull-left'} %>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/tasks/index.html.erb
<div class="container">
    <div class="main-container">
        <div class="project-container">
            <div class="project-main">
                <div class="project-content">
                    <h3><strong><%=  @project.title %></strong></h3>
                    <h4><%=  @project.description %></h4>
                    <br>
                    <h4><i class="fas fa-calendar-alt"></i><strong>   Start date</strong> <%=  @project.start_date %></h4>
                    <h4><i class="fas fa-stopwatch"></i><strong>   Deadline</strong> <%=  @project.deadline %></h4>
                    <h4><i class="fas fa-industry"></i><strong>   Industry</strong> <%=  @project.industry %></h4>
                    <h4><i class="fas fa-clock"></i><strong>   Duration</strong> <%=  @project.nb_hours %> hours</h4>
                    <br>
                    <h4><strong>Client</strong> <%=  @project.client.full_name %></h4>
                    <h4><strong>Expert</strong> <%= @project.expert.nil? ? "Not assigned yet" : @project.expert.full_name %>
                    <% if @project.expert %>
                    <%= link_to conversations_path(sender_id: current_user.id, recipient_id: @project.expert.id), method: "post" do %>
                      <i class="fas fa-envelope"></i>
                    <% end %>
                    <% end %>
                  </h4>
                <br>
            <h4><strong><% if @project.approved %>
              <i class="fas fa-check-circle"></i>
            <% else %>
              <i class="fas fa-times-circle"></i>
            <% end %> Approved </strong></h4>
            <h4><strong><% if @project.status %>
              <i class="fas fa-check-circle"></i>
            <% else %>
              <i class="fas fa-times-circle"></i>
            <% end %> Completed </strong></h4>
            <br>
            <div class="project-task-card-actions">
                <%# if policy(Project.find(params[:project_id])).show? %>
                    <%#= link_to "New deliverable", new_project_task_path, class: "btn btn-success" %>
                <%# end %>
                <%= link_to "Back to projects", projects_path, class: "btn btn-success" %>
              </div>

          </div>
        </div>
    </div>

    <div class="tasks-container">
      <% @tasks.each do |task| %>
        <div class="task-card">
          <div class="row">
            <div class="task-card-content">
              <div class="col-xs-12 col-sm-3">
                <h3 class="task-card-title"><strong><%= task.title %></strong></h3>
                <br>
                <h4 class="task-card-title"><i class="fas fa-calendar-alt"></i>   Start date <%= task.start_date %></h4>
              </div>
              <div class="col-xs-12 col-sm-6">
                <div class="task-card-body">
                  <p><%= task.description %></p>
                </div>
                <div class="task-card-actions">
                  <p>
                  <% if policy(task).edit? %>
                    <%= link_to "Edit", edit_project_task_path( task.project, task) %>
                  <% end %>
                  <%#= link_to "Review", project_tasks_path %>
                  <%  if policy(task).close? && task.status == false %>
                    <%= link_to "Mark complete", edit_task_to_close_path( task.project, task) %>
                  <% end %>
                  <% if policy(task).destroy? %>
                     <%= link_to "Delete", project_task_path(task.project.id, task), method: :delete, data: { confirm: 'Are you sure?' }  %>
                  <% end %>
                  </p>
                </div>
              </div>
              <div class="col-xs-12 col-sm-3">
                <!-- <div>
                  <p>
                    <%#= image_tag "http://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar" %>
                    Expert:  <%#= task.project.expert.nil? ? "Not yet assigned" : task.project.expert.email %>
                  </p>
                </div> -->
                <div class="message-status">
                  <% if task.status == true %>
                  <div class="left-margin">
                    <h4 class="status accepted"><strong>Closed</strong></h4>
                  </div>
                    <br>
                    <h4><i class="fas fa-clock"></i>     Hours</h4>
                    <p>   <%= task.work_hours %></p>
                  <% else %>
                  <div class="left-margin">
                    <h4 class="status pending"><strong>Pending</strong></h4>
                  </div>
                    <br>
                    <h4><i class="fas fa-stopwatch"></i>     Deadline</h4>
                  <div class="left-margin">
                    <p><%= task.deadline %></p>
                  </div>
                  <% end %>


                </div>
              </div>
            </div>
          </div>
        </div>
      <% end %>


          <% if @tasks.empty? %>
              <div class="task-card">
                    <div class="task-card-content">
                        <div class="col-xs-12 col-sm-3"></div>
                        <div class="col-xs-12 col-sm-6">
                            <p>
                                <div class="task-card-body"><h1>NO Task is created</h1></div>
                            </p>
                        </div>
                        <div class="col-xs-12 col-sm-3">
                            <div></div>
                            <div class="message-status"></div>

                        </div>
                    </div>
                </div>
            <% end %>
    </div>
  </div>
</div>

app/views/tasks/new.html.erb
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-sm-8 col-sm-offset-2">
                <div class="form-login">
                    <h2>New deliverable</h2>
                    <%= render 'form' %>
                    <%= link_to "Back", project_tasks_path %>
                </div>
            </div>
        </div>
    </div>