config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :projects do
    resources :tasks, only: [:index, :new, :create, :edit, :update, :destroy]
  end
  resources :users, only: [:index, :show]
  get "profile", to: "pages#profile"
  patch "profile", to: "pages#profile_update"
  get "contact_us", to: "pages#contact_us"

  get "close/:project_id/tasks/:id", to: "tasks#edit_to_close", as: :edit_task_to_close
  patch "/close/:project_id/tasks/:id", to: "tasks#close", as: :closetask

  resources :conversations do
    resources :messages
  end
  # resources :tasks, only: [ :show, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  COUNTRIES =  ['Ethiopia', 'Ghana', 'Ivory Coast', 'Kenya', 'Morocco', 'Nigeria', 'Senegal', 'South Africa', 'Tunisia']
  INDUSTRIES = ["Agriculture", "Construction", "Finance", "Healthcare", "Manufacturing", "Retail", "Technology"]
  YEARS_EXPERIENCE = ["2+ years", "5+ years", "10+ years"]
  HOURS_PER_WEEK = [5, 10, 15, 20, 25, 30, 35]
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :projects
  mount_uploader :photo, PhotoUploader

  def userinfo
    "#{first_name} #{last_name} (#{email})"
  end

  def full_name
    "#{first_name} #{last_name}"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @all_users = policy_scope(User)
    @users = @all_users.where(role: "expert")
    if params[:country] && !params[:country].empty?
      @users = @users.where(country: params[:country])
    end

    if params[:industry] && !params[:industry].empty?
      @users = @users.where(industry: params[:industry])
    end

    if params[:hours_available_per_weeek] && !params[:hours_available_per_weeek].empty?
      @users = @users.where("hours_available_per_weeek > ?", params[:hours_available_per_weeek])
    end
  end

  def show
    @user = User.find(params[:id])
    authorize @user
  end
end

app/views/users/filtered_users.html.erb
<div class="container">
  <% @users.each do |user| %>
  <ul>
    <%= user.email %>
  </ul>
  <% end %>
</div>

app/views/users/index.html.erb
<!-- <div class="container profile-card"> -->
  <!-- <%# @users.each do |user| %>
    <%# if user.role == "expert" %>
      <%# if user.photo.url.nil? %>
        <%#= image_tag "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSd-e9Kn0P1AAKT-EdAiaAVUvBtRVAJqONXIL0pJ402cOAzVi0i", class: "avatar dropdown-toggle", class: "medium-avatar" %>
      <%# else %>
        <%#= cl_image_tag current_user.photo, height: 300, width: 400, crop: :fill, class: "medium-avatar" %>
      <%# end %>
      <!- <div> -->
        <!-- <h3><strong><%#= "#{user.first_name.capitalize} #{user.last_name.capitalize}" %></strong></h3> -->
        <!-- <p><%#= user.email %></p> -->
      <!-- </div> -->
    <%# end %>
  <%# end %> <!-- </div> -->



<div class="filter-container">
  <!-- <div class="container"> -->
    <form action="#" class="form-inline">
    <%= form_tag users_path , method: :get do %>
        <!-- Country: -->
        <!-- <select name="country"> -->
        <select name="country" class="form-control">
          <option value="" hidden>Country</option>
          <option value=""></option>
          <% User::COUNTRIES.each do |country| %>
            <option value="<%= country %>"><%= country %></option>
          <% end %>
        </select>
        <!-- Industry: -->
        <select name="industry" class="form-control">
          <option value="" hidden>Industry</option>
          <option value=""></option>
          <% User::INDUSTRIES.each do |industry| %>
            <option value="<%= industry %>"><%= industry %></option>
          <% end %>
        </select>
    <!--     Availability:
        <select name="availability" class="form-control">
          <option value=""></option>
          <option value="<%#= true %>">Yes</option>
          <option value="<%#= false %>">No</option>
        </select> -->
        <select name="hours_available_per_weeek" class="form-control">
          <option value="" hidden>Availability per week</option>
          <option value=""></option>
            <option value="5">More than 5 hours</option>
            <option value="10">More than 10 hours</option>
            <option value="15">More than 15 hours</option>
            <option value="20">More than 20 hours</option>
        </select>
      <input type="submit" value="filter" class="btn btn-secondary">
    <% end %>
    </form>
<!--   </div> -->
</div>
<div class="container">
  <% @users.each do |user| %>
    <div class="users-card">
      <div class="row">
        <div class="col-xs-12 col-sm-2 flex-center">
          <% if user.photo.url.nil? %>
            <%= image_tag "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSd-e9Kn0P1AAKT-EdAiaAVUvBtRVAJqONXIL0pJ402cOAzVi0i", class: "medium-avatar" %>
          <% else %>
            <%= cl_image_tag user.photo, height: 300, width: 400, crop: :fill, class:"medium-avatar" %>
          <% end %>
        </div>
        <div class="col-xs-12 col-sm-6">
          <h3><%= link_to "#{user.first_name.capitalize} #{user.last_name.capitalize}", user_path(user.id) %></h3>
        </div>
        <div class="col-xs-12 col-sm-6">
          <p><i class="fas fa-map-marker-alt"></i><%= " #{user.country}" %></p>
        </div>
        <div class="col-xs-12 col-sm-6">
          <p><%= "#{user.description[0,200]}..." %></p>
        </div>
      </div>
      <div class="row">
        <div class="col-xs-12 flex-right user-card-actions">
          <%#= link_to "More", user_path(user.id) %>
          <%= link_to conversations_path(sender_id: current_user.id, recipient_id: user.id), method: "post" do %>
            <i class="fas fa-envelope fa-lg"></i>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
  </ul>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="profile-show">
    <div class="row">
        <div class="col-xs-12 col-sm-4 flex-center">
            <% if @user.photo.url.nil? %>
            <%= image_tag "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSd-e9Kn0P1AAKT-EdAiaAVUvBtRVAJqONXIL0pJ402cOAzVi0i", class: "big-avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
            <% else %>
            <%= cl_image_tag @user.photo, height: 300, width: 400, crop: :fill, class:"big-avatar" %>
            <% end %>
        </div>

      <div class="col-xs-12 col-sm-7">
        <h2><%= "#{@user.first_name} #{@user.last_name}"%><%= link_to conversations_path(sender_id: current_user.id, recipient_id: @user.id), method: "post" do %>
            <i class="fas fa-envelope"></i>
          <% end %></h2>
        <h3><strong><%= "#{@user.role.capitalize}"%></strong></h3><br>
      </div>
      <div class="col-xs-12 col-sm-7">
          <h4><i class="fas fa-map-marker-alt"></i><%= "  #{@user.country}" %></h4>
          <h4><i class="fas fa-industry"></i> <%= "  #{@user.industry}" %></h4>
          <h4><i class="fas fa-stopwatch"></i> <%= "  #{@user.hours_available_per_weeek} hours per week" %></h4>
      </div>

      <div class="col-xs-12 col-sm-7"><br>
        <p><%= @user.description %></p><br>
        <!-- <p><strong>Contact: <%= @user.email %></p></strong> -->

      </div>
    </div>
  </div>
</div>