config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :projects do
    resources :tasks, only: [:index, :new, :create, :edit, :update, :destroy]
  end
  resources :users, only: [:index, :show]
  get "profile", to: "pages#profile"
  patch "profile", to: "pages#profile_update"
  get "contact_us", to: "pages#contact_us"

  get "close/:project_id/tasks/:id", to: "tasks#edit_to_close", as: :edit_task_to_close
  patch "/close/:project_id/tasks/:id", to: "tasks#close", as: :closetask

  resources :conversations do
    resources :messages
  end
  # resources :tasks, only: [ :show, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.svg" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>
    <a href="#" class="navbar-wagon-item navbar-wagon-link"><%= current_user.email %></a>
    <% end %>
      <!-- Links when logged in -->
      <%= link_to "About us", "#", class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Our services", "#", class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Contact us", contact_us_path, class: "navbar-wagon-item navbar-wagon-link" %>

    <% if user_signed_in? %>
      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <% if current_user.photo.url.nil? %>
            <%= image_tag "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSd-e9Kn0P1AAKT-EdAiaAVUvBtRVAJqONXIL0pJ402cOAzVi0i", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
            <% if (current_user.role == "manager") && (Project.pending != "0")%><span class="badge"><%=  Project.pending %></span><% end %>
          <% else %>
            <%= cl_image_tag current_user.photo, height: 300, width: 400, crop: :fill, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <% end %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to profile_path do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to conversations_path do %>
                <%= t(".conversation_messages", default: "Messages") %>
              <% end %>
            </li>
            <li>
              <%= link_to projects_path do %>
                <%= t(".projects", default: "Projects") %>
              <% end %>
            </li>
            <% if current_user.role == "manager" %>
              <li>
                <%= link_to users_path do %>
                  <%= t(".experts", default: "Experts")  %>
                <% end %>
              </li>
            <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <% if user_signed_in? %>
          <li><%= link_to "Profile", profile_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
          <li><%= link_to "Projects", projects_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
          <li><%= link_to "Contact us", contact_us_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
          <li><%= link_to t(".sign_out", default: "Log out"), destroy_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
        <% else %>
        <li><%= link_to "Who we are", "#", class: "navbar-wagon-item navbar-wagon-link" %></li>
        <li><%= link_to "How it works", "#", class: "navbar-wagon-item navbar-wagon-link" %></li>
        <li><%= link_to "Our services", "#", class: "navbar-wagon-item navbar-wagon-link" %></li>
        <li><%= link_to "Contact us", contact_us_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
        <li><%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>