config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :projects do
    resources :tasks, only: [:index, :new, :create, :edit, :update, :destroy]
  end
  resources :users, only: [:index, :show]
  get "profile", to: "pages#profile"
  patch "profile", to: "pages#profile_update"
  get "contact_us", to: "pages#contact_us"

  get "close/:project_id/tasks/:id", to: "tasks#edit_to_close", as: :edit_task_to_close
  patch "/close/:project_id/tasks/:id", to: "tasks#close", as: :closetask

  resources :conversations do
    resources :messages
  end
  # resources :tasks, only: [ :show, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :client, class_name: 'User', foreign_key: 'client_id', optional: true
  belongs_to :manager, class_name: 'User', foreign_key: 'manager_id', optional: true
  belongs_to :expert, class_name: 'User', foreign_key: 'expert_id', optional: true
  belongs_to :client_review, class_name: 'Review', foreign_key: 'client_review_id', optional: true, dependent: :destroy
  belongs_to :expert_review, class_name: 'Review', foreign_key: 'expert_review_id', optional: true, dependent: :destroy
  has_many :tasks, dependent: :destroy

   scope :pending, -> () {
    self.where(approved: false).count.to_s
   }
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  def index
    #@projects = policy_scope(Project).order(created_at: :desc)
    case current_user.role
      when "manager"
        @projects = policy_scope(Project).order(created_at: :desc)#.where(manager: current_user)
      when "expert"
        @projects = policy_scope(Project).where(expert: current_user).order(created_at: :desc)
      when "client"
        @projects = policy_scope(Project).where(client: current_user).order(created_at: :desc)
    end

  end

  def show
  end

  def new
    @project = Project.new
    authorize @project
  end

  def create
    #raise
    @project = Project.new(project_params)
    case current_user.role
      when "manager"
        @project.manager = current_user
        @project.client = nil
        @project.expert = nil
      when "expert"
        @project.manager = nil
        @project.client = nil
        @project.expert = current_user
      when "client"
        @project.manager = nil
        @project.client = current_user
        @project.expert = nil
    end
    @project.status = false
    authorize @project
    if @project.save

      create_tasks(@project)

      redirect_to project_path(@project), notice: 'Project was successfully created'
    else
      render :new
    end
  end

  def edit
  end

  def update
    @project.update(project_params)
    destroy_tasks(@project)
    create_tasks(@project)
    redirect_to projects_path
  end

  def destroy
    @project.destroy
    redirect_to projects_path
  end

  private

  def destroy_tasks(project)
    project.tasks.each do |task|
      task.destroy
    end
  end

  def create_tasks(project)
    div = project.nb_hours / project.nb_tasks
    rest = project.nb_hours.modulo(project.nb_tasks)
    #create tasks
    project.nb_tasks.times do |i|
      if i == (project.nb_tasks - 1)
        div += rest
      end
      task = Task.create(
        title: "Deliverable " + (i + 1).to_s,
        description: project.description,
        project: project,
        work_hours: div,
        status: false
      )
    end
  end

  def set_project
    @project = Project.find(params[:id])
    authorize @project
  end

  def project_params
    params.require(:project).permit(:title, :description, :start_date, :end_date, :deadline, :nb_hours, :expertise_level, :industry, :country, :nb_tasks, :manager_id, :expert_id, :approved)
  end
end

app/views/projects/_form.html.erb
<%= simple_form_for [@project] do |f| %>
  <%= f.input :title , label_html: {class: 'pull-left'}%>
  <%= f.input :description, label_html: {class: 'pull-left'} %>
  <%= f.input :industry, collection: User::INDUSTRIES, label_html: {class: 'pull-left'} %>
  <%= f.input :country, collection: User::COUNTRIES, label_html: {class: 'pull-left'} %>
  <%= f.input :expertise_level, collection: ["Research Analyst: 0-2 years experience", "Research Specialist: 2-5 years experience", "Research Specialist: more than 5 years experience"], label_html: {class: 'pull-left'} %>
  <%= f.input :start_date, label_html: {class: 'pull-left'}, as: :date, html5: true %>
  <%= f.input :deadline, label_html: {class: 'pull-left'}, as: :date, html5: true %>
  <%= f.input :nb_hours, label: 'Total number of hours',label_html: {class: 'pull-left'} %>
  <%= f.input :nb_tasks, label: 'Number of deliverables', label_html: {class: 'pull-left'} %>
  <% if @project.id == nil %>
    <%= f.submit "add project", class: "btn btn-primary" %>
    <% else %>

      <% if policy(@project).edit? %>
       <%= f.input :manager_id, collection: User.where(role: "manager"), label_method: :userinfo, value_method: :id, label_html: {class: 'pull-left'} %>
       <%= f.input :expert_id, collection: User.where(role: "expert"), label_method: :userinfo, value_method: :id, label_html: {class: 'pull-left'} %>
        <%= f.input :approved,
                    label: "Status",
                    collection: [[true, 'Approved'], [false, 'Pending']],
                    include_blank: false,
                    label_method: :last,
                    label_html: {class: 'pull-left'},
                    :value_method => :first
        %>
      <% end %>
    <%= f.submit "Save changes", class: "btn btn-primary" %>

  <% end %>
<% end %>

app/views/projects/_project_card.html.erb
<div class="project-card">
    <div class="row">
        <div class='col-xs-12 col-sm-8'>
            <h3 class="project-card-title"><strong><%= link_to project.title, project_tasks_path(project) %></strong></h3>
            <p class="project-card-content font-size-big">
                <%= project.description %>
            </p><br>
        </div>
        <div class="col-xs-12 col-sm-4 flex-right">
            <p class="project-card-content font-size-big">
                <% project.tasks.each do |task| %>
                  <% if task.status == false %>
                    <% if policy(task).edit? %>
                        <%= link_to  edit_project_task_path(project, task) do %>
                          <i class="fas fa-square fa-green"></i>
                        <% end %>
                    <% else %>
                        <i class="fas fa-square fa-green"></i>
                    <% end %>
                  <% else %>
                    <% if policy(task).edit? %>
                      <%= link_to  edit_project_task_path(project, task) do %>
                        <i class="fas fa-square fa-gray"></i>
                      <% end %>
                    <% else %>
                      <i class="fas fa-square fa-gray"></i>
                    <% end %>
                  <% end %>
                <% end %>
            </p>
        </div>
    </div>

    <div class="row">
        <div class='col-xs-12 col-sm-8'>
            <p class="project-card-content font-size-big"><i class="fas fa-user-tie"></i><strong>   Manager</strong>    <%= project.manager.nil? ? "Not assigned yet" : project.manager.full_name %>
            </p>
            <p class="project-card-content font-size-big"><i class="fas fa-phone"></i><strong>   Client</strong>
                <%= project.client.full_name %> (<%= project.client.phone_number.nil? ? " " : project.client.phone_number %>)
            </p>
            <p class="project-card-content font-size-big"><i class="fas fa-industry"></i><strong>   Industry</strong>
                <%= project.industry %>
            </p>
            <p class="project-card-content font-size-big"><i class="fas fa-map-marker-alt"></i><strong>   Country</strong>
                <%= project.country %>
            </p>
            <p class="project-card-content font-size-big"><i class="fas fa-user"></i><strong>   Expert</strong>
                <%= project.expert.nil? ? "Not assigned yet" : project.expert.full_name %>
                    <% if project.expert %>
                    <%= link_to conversations_path(sender_id: current_user.id, recipient_id: project.expert.id), method: "post" do %>
                      <i class="fas fa-envelope"></i>
                    <% end %>
                    <% end %>
            </p>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12 flex-right">
            <div class="project-card-actions">
                <%= link_to "Deliverables", project_tasks_path(project) %>
                <% if policy(project).edit? %>
                <%= link_to "Edit", edit_project_path(project.id) %>
                <% end %>
                <% if policy(project).destroy? %>
                <%= link_to "Delete", project_path(project), method: :delete, data: {confirm: 'Are you sure?'} %>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/projects/edit.html.erb
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-sm-8 col-sm-offset-2">
                <div class="form-login">
                    <h2>Edit Project</h2>
                    <%= render 'form', project: @project %>
                </div>
            </div>
        </div>
    </div>

app/views/projects/index.html.erb
<div class="wrap container">

  <div class="project-nav">
    <!-- Nav tabs -->
    <ul class="nav nav-tabs nav-justified" role="tablist">
      <li role="presentation" class="active"><a href="#current-projects" aria-controls="current-projects" role="tab" data-toggle="tab">Current projects</a></li>
      <li role="presentation"><a href="#pending-projects" aria-controls="pending-projects" role="tab" data-toggle="tab">Pending projects</a></li>
      <li role="presentation"><a href="#past-projects" aria-controls="past-projects" role="tab" data-toggle="tab">Past projects</a></li>
    </ul>

    <!-- Tab panes -->
    <div class="tab-content">
      <div role="tabpanel" class="tab-pane active" id="current-projects">
        <% @projects.where(approved: true, status: false).each do |project| %>
          <%= render "project_card", project: project %>
        <% end %>
      </div>
      <div role="tabpanel" class="tab-pane" id="pending-projects">
        <% @projects.where(approved: false, status: false).each do |project| %>
          <%= render "project_card", project: project %>
        <% end %>
      </div>
      <div role="tabpanel" class="tab-pane" id="past-projects">
        <% @projects.where(approved: true, status: true).each do |project| %>
          <%= render "project_card", project: project %>
        <% end %>
      </div>
    </div>
  </div>

</div>

app/views/projects/new.html.erb
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-sm-8 col-sm-offset-2">
                <div class="form-login">
                    <h2>New Project</h2>
                    <%= render 'form' %>
                    <%= link_to "Back to projects", projects_path %>
                </div>
            </div>
        </div>
    </div>

app/views/projects/show.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(50,50,50,0.8) 0%, rgba(50,50,50,0.7) 50%), url('https://images.unsplash.com/photo-1521798416081-5c2c473b6533?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2037&q=80');">
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-sm-12">
              <h1>Your request has been submitted.</h1>
              <h3>We will get back to you within 48 hours.</h3><br>
              <%= link_to "Back to projects", projects_path, class: "btn btn-primary" %>
            </div>
        </div>
    </div>
</div>